name: react_native
version: 1.1.1
description: A sample command-line application.
environment: 
  sdk: ^3.2.0
dependencies:
  cwa_plugin_core: 
    git: 
      url: git@gitlab.com-codewave:codewave-technologies/cwa_plugin_core.git
      ref: main
  cw_core: 
    git: 
      url: git@gitlab.com-codewave:codewave-technologies/codewave-flutter-core.git
      ref: main
  cli_spin: ^1.0.1
  process_run: ^0.12.4

dev_dependencies: 
  lints: ^4.0.0
  test: ^1.24.0
