name: react_native
version: 1.0.0
description: A sample command-line application.
environment: 
  sdk: ^3.2.0
dependencies:
  cwa_plugin_core: 
    git: 
      url: git@gitlab.com-codewave:codewave-technologies/cwa_plugin_core.git
      ref: main
  cw_core: 
    git: 
      url: git@gitlab.com-codewave:codewave-technologies/codewave-flutter-core.git
      ref: main
dev_dependencies: 
  lints: ^4.0.0
  test: ^1.24.0
